### ISSUE TITLE
Issue in 02-sensors.py

### ISSUE THREAD

**Issue by kunalgarg42** [dawsonc/tello-x#1]
I get the following error when I run the 02-sensors.py file. I believe it is because of the variable last_takeoff_time not defined in init() unless the function takeoff() is called in Pilot file. 

Traceback (most recent call last):
  File "...\tello-x\scripts\02-sensors.py", line 16, in <module>
    readings.append(pilot.get_sensor_readings())
                   
  File "...\tello-x\tellox\pilot.py", line 157, in get_sensor_readings
    flight_time = time.time() - self.last_takeoff_time

**Comment by dawsonc** [comment]
Thanks for flagging this! This should be fixed in[ `0.2.7`](https://github.com/dawsonc/tello-x/releases/tag/v0.2.7). Try `pip install tellox --upgrade` to get the new version. I changed the default behavior so that `last_takeoff_time` is set to the current time during `init` and then re-set during `takeoff`.
